version: 0.2

phases:
  install:
    commands:
      - echo "install"
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build -t ${REPOSITORY_URI}:latest .
  # post_build:
  #   commands:
  #     - docker push ${REPOSITORY_URI}:latest
