version: 0.2

phases:
  install:
    commands:
      - echo "install"
  pre_build:
    commands:
      - $(aws --version)
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build -t ${IMAGE_REPO_NAME}:latest .
      - docker tag ${IMAGE_REPO_NAME}:latest ${REPOSITORY_URI}
  post_build:
    commands:
      - docker push ${REPOSITORY_URI}:latest
